device: "cpu"
training_type: "single_step" #or "solver_in_the_loop"

# Network
net:
  n_input: 1
  n_output: 1
  n_hidden: 20
  n_layers: 5
  
  activation: "Tanh"
  with_pretrain: False

# Optimizer
opt:
  n_epochs: 150
  lr: 1e-3
  weight_decay: 0.0

  scheduler: "ReduceLROnPlateau" #'ReduceLROnPlateau' or 'CosineAnnealingLR'
  factor: 0.5      # for ReduceLROnPlateau only
  patience: 10     # for ReduceLROnPlateau only

  grad_clipping: False

# Solver for linear advection
solver:
  initial_data: "sin_wave" # step, square_wave, sin_wave
  t_end: 10.
  velocity: 1.
  n_cells: 100
  CFL: 0.4

data:
  folder: '~/research/flux_limiter/data/'
  filename: '1D_Advection_Sols_beta1.0_single_step.npy'
  batch_size: 50
  n_train: 9000
  test_batch_size: 50
  n_test: 1000
  spatial_length: 1024
  temporal_length: 2
  xL: 0.
  xR: 1.
  dt: 3.90625e-4

wandb:
  log: False




