device: "cpu"

# Network
net:
  n_input: 1
  n_output: 1
  n_hidden: 20
  n_layers: 5
  
  activation: "Tanh"
  with_pretrain: False

# Optimizer
opt:
  n_epochs: 8
  lr: 1e-3
  weight_decay: 0.0

  scheduler: "CosineAnnealingLR" #'ReduceLROnPlateau' or 'CosineAnnealingLR'
  factor: 0.5      # for ReduceLROnPlateau
  patience: 10     # for ReduceLROnPlateau

  grad_clipping: False


# Solver for linear advection
solver:
  initial_data: "sin_wave" # step, square_wave, sin_wave
  t_end: 10.
  velocity: 1.
  n_cells: 100
  CFL: 0.5





